import React from 'react';
import { Outlet, Link } from "react-router-dom";
import { APP_NAME, ROUTES } from "@/constants/routes";
function AuthLayout() {
  return /* @__PURE__ */ React.createElement("div", { className: "flex min-h-screen" }, /* @__PURE__ */ React.createElement("div", { className: "hidden flex-1 flex-col justify-between bg-gradient-hero p-12 lg:flex" }, /* @__PURE__ */ React.createElement(Link, { to: ROUTES.landing.home, className: "flex items-center gap-2" }, /* @__PURE__ */ React.createElement("div", { className: "flex h-10 w-10 items-center justify-center rounded-full bg-gradient-brand shadow-lg shadow-primary/30" }, /* @__PURE__ */ React.createElement("span", { className: "text-lg font-bold text-white" }, "T")), /* @__PURE__ */ React.createElement("span", { className: "font-heading text-xl font-bold text-text-primary" }, APP_NAME)), /* @__PURE__ */ React.createElement("div", { className: "max-w-md" }, /* @__PURE__ */ React.createElement("blockquote", { className: "text-h2 font-bold leading-snug tracking-tight text-text-primary" }, "\u201CTendo transformed how we run our massage clinic. Scheduling and charting save us hours every week.\u201D"), /* @__PURE__ */ React.createElement("p", { className: "mt-4 text-body text-text-secondary" }, "\u2014 Sarah Chen, Harmony Wellness RMT \xB7 Vancouver, BC")), /* @__PURE__ */ React.createElement("p", { className: "text-body-sm text-text-muted" }, "PIPEDA compliant \xB7 256-bit encryption \xB7 99.9% uptime")), /* @__PURE__ */ React.createElement("div", { className: "flex flex-1 flex-col items-center justify-center px-4 py-12" }, /* @__PURE__ */ React.createElement(Link, { to: ROUTES.landing.home, className: "mb-8 flex items-center gap-2 lg:hidden" }, /* @__PURE__ */ React.createElement("div", { className: "flex h-8 w-8 items-center justify-center rounded-full bg-gradient-brand" }, /* @__PURE__ */ React.createElement("span", { className: "text-sm font-bold text-white" }, "T")), /* @__PURE__ */ React.createElement("span", { className: "font-heading text-lg font-bold" }, APP_NAME)), /* @__PURE__ */ React.createElement("div", { className: "w-full max-w-md" }, /* @__PURE__ */ React.createElement(Outlet, null))));
}
export {
  AuthLayout
};
